// next-app/src/components/common/CodeEditor.tsx
'use client';

import { useEffect, useRef, useCallback, useImperativeHandle, forwardRef } from 'react';
import { basicSetup, EditorView } from 'codemirror';
import { keymap, placeholder } from '@codemirror/view';
import { Compartment, EditorState } from '@codemirror/state';
import { acceptCompletion } from '@codemirror/autocomplete';
import { indentWithTab } from '@codemirror/commands';
import { indentUnit, LanguageDescription } from '@codemirror/language';
import { languages } from '@codemirror/language-data';
import { oneDark } from '@codemirror/theme-one-dark';

interface CodeEditorProps {
	id?: string;
	value: string;
	onChange: (value: string) => void;
	onSave?: () => void;
	lang?: string;
	boilerplate?: string;
}

export interface CodeEditorRef {
	focus: () => void;
	formatPythonCode: () => Promise<boolean>;
}

function findChanges(oldStr: string, newStr: string) {
	let start = 0;
	while (start < oldStr.length && start < newStr.length && oldStr[start] === newStr[start]) {
		start++;
	}
	if (oldStr === newStr) return [];
	let endOld = oldStr.length,
		endNew = newStr.length;
	while (endOld > start && endNew > start && oldStr[endOld - 1] === newStr[endNew - 1]) {
		endOld--;
		endNew--;
	}
	return [
		{
			from: start,
			to: endOld,
			insert: newStr.slice(start, endNew)
		}
	];
}

export const CodeEditor = forwardRef<CodeEditorRef, CodeEditorProps>(
	({ id = '', value, onChange, onSave, lang = '', boilerplate = '' }, ref) => {
		const containerRef = useRef<HTMLDivElement>(null);
		const editorRef = useRef<EditorView | null>(null);
		const valueRef = useRef(value || boilerplate);
		const editorTheme = useRef(new Compartment());
		const editorLanguage = useRef(new Compartment());
		const isDarkModeRef = useRef(false);

		const getLang = useCallback(async () => {
			const language = languages.find((l) => l.alias.includes(lang));
			return language?.load();
		}, [lang]);

		useImperativeHandle(ref, () => ({
			focus: () => {
				editorRef.current?.focus();
			},
			formatPythonCode: async () => {
				return false;
			}
		}));

		useEffect(() => {
			if (!containerRef.current) return;

			isDarkModeRef.current = document.documentElement.classList.contains('dark');

			const extensions = [
				basicSetup,
				keymap.of([{ key: 'Tab', run: acceptCompletion }, indentWithTab]),
				indentUnit.of('    '),
				placeholder('Enter your code here...'),
				EditorView.updateListener.of((e) => {
					if (e.docChanged) {
						valueRef.current = e.state.doc.toString();
						onChange(valueRef.current);
					}
				}),
				editorTheme.current.of([]),
				editorLanguage.current.of([])
			];

			const editor = new EditorView({
				state: EditorState.create({
					doc: valueRef.current,
					extensions
				}),
				parent: containerRef.current
			});

			editorRef.current = editor;

			if (isDarkModeRef.current) {
				editor.dispatch({
					effects: editorTheme.current.reconfigure(oneDark)
				});
			}

			const observer = new MutationObserver((mutations) => {
				mutations.forEach((mutation) => {
					if (mutation.type === 'attributes' && mutation.attributeName === 'class') {
						const newIsDarkMode = document.documentElement.classList.contains('dark');
						if (newIsDarkMode !== isDarkModeRef.current) {
							isDarkModeRef.current = newIsDarkMode;
							if (newIsDarkMode) {
								editor.dispatch({
									effects: editorTheme.current.reconfigure(oneDark)
								});
							} else {
								editor.dispatch({
									effects: editorTheme.current.reconfigure([])
								});
							}
						}
					}
				});
			});

			observer.observe(document.documentElement, {
				attributes: true,
				attributeFilter: ['class']
			});

			const keydownHandler = (e: KeyboardEvent) => {
				if ((e.ctrlKey || e.metaKey) && e.key === 's') {
					e.preventDefault();
					onSave?.();
				}
			};

			document.addEventListener('keydown', keydownHandler);

			return () => {
				observer.disconnect();
				document.removeEventListener('keydown', keydownHandler);
				editor.destroy();
			};
		}, [onChange, onSave]);

		useEffect(() => {
			const setLanguage = async () => {
				const language = await getLang();
				if (language && editorRef.current) {
					editorRef.current.dispatch({
						effects: editorLanguage.current.reconfigure(language)
					});
				}
			};
			setLanguage();
		}, [lang, getLang]);

		useEffect(() => {
			if (editorRef.current && value !== valueRef.current) {
				const changes = findChanges(valueRef.current, value);
				valueRef.current = value;
				if (changes.length > 0) {
					editorRef.current.dispatch({ changes });
				}
			}
		}, [value]);

		return <div ref={containerRef} id={`code-textarea-${id}`} className="h-full w-full text-sm" />;
	}
);

CodeEditor.displayName = 'CodeEditor';

// src/lib/components/common/CodeEditor.svelte
<script lang="ts">
	import { basicSetup, EditorView } from 'codemirror';
	import { keymap, placeholder } from '@codemirror/view';
	import { Compartment, EditorState } from '@codemirror/state';

	import { acceptCompletion } from '@codemirror/autocomplete';
	import { indentWithTab } from '@codemirror/commands';

	import { indentUnit, LanguageDescription } from '@codemirror/language';
	import { languages } from '@codemirror/language-data';

	import { oneDark } from '@codemirror/theme-one-dark';

	import { onMount, createEventDispatcher, tick } from 'svelte';

	import { formatPythonCode } from '$lib/apis/utils';
	import { toast } from 'svelte-sonner';

	const dispatch = createEventDispatcher();
	export let boilerplate = '';
	export let value = '';

	export let onSave = () => {};
	export let onChange = () => {};

	let _value = '';

	$: if (value) {
		updateValue();
	}

	const updateValue = () => {
		if (_value !== value) {
			const changes = findChanges(_value, value);
			_value = value;

			if (codeEditor && changes.length > 0) {
				codeEditor.dispatch({ changes });
			}
		}
	};

	/**
	 * Finds multiple diffs in two strings and generates minimal change edits.
	 */
	function findChanges(oldStr: string, newStr: string) {
		// Find the start of the difference
		let start = 0;
		while (start < oldStr.length && start < newStr.length && oldStr[start] === newStr[start]) {
			start++;
		}
		// If equal, nothing to change
		if (oldStr === newStr) return [];
		// Find the end of the difference by comparing backwards
		let endOld = oldStr.length,
			endNew = newStr.length;
		while (endOld > start && endNew > start && oldStr[endOld - 1] === newStr[endNew - 1]) {
			endOld--;
			endNew--;
		}
		return [
			{
				from: start,
				to: endOld,
				insert: newStr.slice(start, endNew)
			}
		];
	}

	export let id = '';
	export let lang = '';

	let codeEditor;

	export const focus = () => {
		codeEditor.focus();
	};

	let isDarkMode = false;
	let editorTheme = new Compartment();
	let editorLanguage = new Compartment();

	languages.push(
		LanguageDescription.of({
			name: 'HCL',
			extensions: ['hcl', 'tf'],
			load() {
				return import('codemirror-lang-hcl').then((m) => m.hcl());
			}
		})
	);
	languages.push(
		LanguageDescription.of({
			name: 'Elixir',
			extensions: ['ex', 'exs'],
			load() {
				return import('codemirror-lang-elixir').then((m) => m.elixir());
			}
		})
	);

	const getLang = async () => {
		const language = languages.find((l) => l.alias.includes(lang));
		return await language?.load();
	};

	export const formatPythonCodeHandler = async () => {
		if (codeEditor) {
			const res = await formatPythonCode(localStorage.token, _value).catch((error) => {
				toast.error(`${error}`);
				return null;
			});
			if (res && res.code) {
				const formattedCode = res.code;
				codeEditor.dispatch({
					changes: [{ from: 0, to: codeEditor.state.doc.length, insert: formattedCode }]
				});

				_value = formattedCode;
				onChange(_value);
				await tick();

				toast.success('Code formatted successfully');
				return true;
			}
			return false;
		}
		return false;
	};

	let extensions = [
		basicSetup,
		keymap.of([{ key: 'Tab', run: acceptCompletion }, indentWithTab]),
		indentUnit.of('    '),
		placeholder('Enter your code here...'),
		EditorView.updateListener.of((e) => {
			if (e.docChanged) {
				_value = e.state.doc.toString();
				onChange(_value);
			}
		}),
		editorTheme.of([]),
		editorLanguage.of([])
	];

	$: if (lang) {
		setLanguage();
	}

	const setLanguage = async () => {
		const language = await getLang();
		if (language && codeEditor) {
			codeEditor.dispatch({
				effects: editorLanguage.reconfigure(language)
			});
		}
	};

	onMount(() => {
		if (value === '') {
			value = boilerplate;
		}

		_value = value;

		// Check if html class has dark mode
		isDarkMode = document.documentElement.classList.contains('dark');

		// python code editor, highlight python code
		codeEditor = new EditorView({
			state: EditorState.create({
				doc: _value,
				extensions: extensions
			}),
			parent: document.getElementById(`code-textarea-${id}`)
		});

		if (isDarkMode) {
			codeEditor.dispatch({
				effects: editorTheme.reconfigure(oneDark)
			});
		}

		// listen to html class changes this should fire only when dark mode is toggled
		const observer = new MutationObserver((mutations) => {
			mutations.forEach((mutation) => {
				if (mutation.type === 'attributes' && mutation.attributeName === 'class') {
					const _isDarkMode = document.documentElement.classList.contains('dark');

					if (_isDarkMode !== isDarkMode) {
						isDarkMode = _isDarkMode;
						if (_isDarkMode) {
							codeEditor.dispatch({
								effects: editorTheme.reconfigure(oneDark)
							});
						} else {
							codeEditor.dispatch({
								effects: editorTheme.reconfigure()
							});
						}
					}
				}
			});
		});

		observer.observe(document.documentElement, {
			attributes: true,
			attributeFilter: ['class']
		});

		const keydownHandler = async (e) => {
			if ((e.ctrlKey || e.metaKey) && e.key === 's') {
				e.preventDefault();

				onSave();
			}

			// Format code when Ctrl + Shift + F is pressed
			if ((e.ctrlKey || e.metaKey) && e.shiftKey && e.key === 'f') {
				e.preventDefault();
				await formatPythonCodeHandler();
			}
		};

		document.addEventListener('keydown', keydownHandler);

		return () => {
			observer.disconnect();
			document.removeEventListener('keydown', keydownHandler);
		};
	});
</script>

<div id="code-textarea-{id}" class="h-full w-full text-sm" />
