// next-app/src/components/common/Image.tsx
'use client';

import { useState } from 'react';
import { WEBUI_BASE_URL } from '@/lib/constants';
import { useAppStore } from '@/store';
import { ImagePreview } from './ImagePreview';
import { X } from 'lucide-react';

interface ImageProps {
  src: string;
  alt?: string;
  className?: string;
  imageClassName?: string;
  dismissible?: boolean;
  onDismiss?: () => void;
}

export function Image({
  src,
  alt = '',
  className,
  imageClassName = 'rounded-lg',
  dismissible = false,
  onDismiss,
}: ImageProps) {
  const settings = useAppStore((state) => state.settings);
  const [showImagePreview, setShowImagePreview] = useState(false);

  const highContrastMode = settings?.highContrastMode ?? false;
  const containerClassName =
    className ?? `w-full ${highContrastMode ? '' : 'outline-hidden focus:outline-hidden'}`;

  const resolvedSrc = src.startsWith('/') ? `${WEBUI_BASE_URL}${src}` : src;

  return (
    <>
      <ImagePreview
        show={showImagePreview}
        onClose={() => setShowImagePreview(false)}
        src={resolvedSrc}
        alt={alt}
      />

      <div className="relative group w-fit flex items-center">
        <button
          className={containerClassName}
          onClick={() => setShowImagePreview(true)}
          aria-label="Show image preview"
          type="button"
        >
          <img
            src={resolvedSrc}
            alt={alt}
            className={imageClassName}
            draggable={false}
            data-cy="image"
          />
        </button>

        {dismissible && (
          <div className="absolute -top-1 -right-1">
            <button
              aria-label="Remove image"
              className="bg-white text-black border border-white rounded-full group-hover:visible invisible transition"
              type="button"
              onClick={onDismiss}
            >
              <X className="size-4" />
            </button>
          </div>
        )}
      </div>
    </>
  );
}

// src/lib/components/common/Image.svelte
<script lang="ts">
	import { WEBUI_BASE_URL } from '$lib/constants';

	import { settings } from '$lib/stores';
	import ImagePreview from './ImagePreview.svelte';
	import XMark from '$lib/components/icons/XMark.svelte';

	export let src = '';
	export let alt = '';

	export let className = ` w-full ${($settings?.highContrastMode ?? false) ? '' : 'outline-hidden focus:outline-hidden'}`;

	export let imageClassName = 'rounded-lg';

	export let dismissible = false;
	export let onDismiss = () => {};
	let _src = '';
	$: _src = src.startsWith('/') ? `${WEBUI_BASE_URL}${src}` : src;

	let showImagePreview = false;
</script>

<ImagePreview bind:show={showImagePreview} src={_src} {alt} />

<div class=" relative group w-fit flex items-center">
	<button
		class={className}
		on:click={() => {
			showImagePreview = true;
		}}
		aria-label={'Show image preview'}
		type="button"
	>
		<img src={_src} {alt} class={imageClassName} draggable="false" data-cy="image" />
	</button>

	{#if dismissible}
		<div class=" absolute -top-1 -right-1">
			<button
				aria-label={'Remove image'}
				class=" bg-white text-black border border-white rounded-full group-hover:visible invisible transition"
				type="button"
				on:click={() => {
					onDismiss();
				}}
			>
				<XMark className={'size-4'} />
			</button>
		</div>
	{/if}
</div>
