// next-app/src/components/layout/Sidebar/UserMenu.tsx
'use client';

import { useState, useEffect, ReactNode } from 'react';
import Link from 'next/link';
import * as DropdownMenuPrimitive from '@radix-ui/react-dropdown-menu';
import { useRouter } from 'next/navigation';
import { Tooltip } from '@/components/common/Tooltip';
import { useAppStore, useUIStore } from '@/store';
import { Settings, ArchiveBox, UserGroup, SignOut, QuestionMarkCircle, Keyboard } from '@/components/icons';

interface UserMenuProps {
  role?: string;
  help?: boolean;
  className?: string;
  onShow?: (type: string) => void;
  children: ReactNode;
}

export function UserMenu({
  role = '',
  help = false,
  className = 'max-w-[240px]',
  onShow,
  children,
}: UserMenuProps) {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [usage, setUsage] = useState<{ user_ids?: string[]; model_ids?: string[] } | null>(null);

  const mobile = useAppStore((s) => s.mobile);
  const user = useAppStore((s) => s.user);
  const setUser = useAppStore((s) => s.setUser);
  const setShowSettings = useUIStore((s) => s.setShowSettings);
  const setShowSidebar = useUIStore((s) => s.setShowSidebar);
  const setShowShortcuts = useUIStore((s) => s.setShowShortcuts);

  useEffect(() => {
    if (open) {
      // Fetch usage info when menu opens
      // getUsage would be implemented in the API layer
    }
  }, [open]);

  const handleSignOut = async () => {
    try {
      // Call sign out API
      const response = await fetch('/api/auths/signout', { method: 'POST' });
      const data = await response.json();

      setUser(undefined);
      localStorage.removeItem('token');

      window.location.href = data?.redirect_url ?? '/auth';
    } catch (error) {
      console.error('Sign out error:', error);
      window.location.href = '/auth';
    }
    setOpen(false);
  };

  return (
    <DropdownMenuPrimitive.Root open={open} onOpenChange={setOpen}>
      <DropdownMenuPrimitive.Trigger asChild>
        {children}
      </DropdownMenuPrimitive.Trigger>

      <DropdownMenuPrimitive.Portal>
        <DropdownMenuPrimitive.Content
          className={`w-full ${className} rounded-2xl px-1 py-1 border border-gray-100 dark:border-gray-800 z-50 bg-white dark:bg-gray-850 dark:text-white shadow-lg text-sm`}
          sideOffset={4}
          side="top"
          align="end"
        >
          <DropdownMenuPrimitive.Item
            className="flex rounded-xl py-1.5 px-3 w-full hover:bg-gray-50 dark:hover:bg-gray-800 transition cursor-pointer outline-none"
            onSelect={async () => {
              setOpen(false);
              setShowSettings(true);
              if (mobile) {
                setShowSidebar(false);
              }
            }}
          >
            <div className="self-center mr-3">
              <Settings className="w-5 h-5" strokeWidth={1.5} />
            </div>
            <div className="self-center truncate">Settings</div>
          </DropdownMenuPrimitive.Item>

          <DropdownMenuPrimitive.Item
            className="flex rounded-xl py-1.5 px-3 w-full hover:bg-gray-50 dark:hover:bg-gray-800 transition cursor-pointer outline-none"
            onSelect={() => {
              setOpen(false);
              onShow?.('archived-chat');
              if (mobile) {
                setShowSidebar(false);
              }
            }}
          >
            <div className="self-center mr-3">
              <ArchiveBox className="size-5" strokeWidth={1.5} />
            </div>
            <div className="self-center truncate">Archived Chats</div>
          </DropdownMenuPrimitive.Item>

          {role === 'admin' && (
            <DropdownMenuPrimitive.Item asChild>
              <Link
                href="/admin"
                className="flex rounded-xl py-1.5 px-3 w-full hover:bg-gray-50 dark:hover:bg-gray-800 transition select-none outline-none"
                onClick={() => {
                  setOpen(false);
                  if (mobile) {
                    setShowSidebar(false);
                  }
                }}
              >
                <div className="self-center mr-3">
                  <UserGroup className="w-5 h-5" strokeWidth={1.5} />
                </div>
                <div className="self-center truncate">Admin Panel</div>
              </Link>
            </DropdownMenuPrimitive.Item>
          )}

          {help && (
            <>
              <DropdownMenuPrimitive.Separator className="border-gray-50 dark:border-gray-800 my-1" />

              {user?.role === 'admin' && (
                <>
                  <DropdownMenuPrimitive.Item asChild>
                    <a
                      href="https://docs.openwebui.com"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex gap-3 items-center py-1.5 px-3 text-sm select-none w-full cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-800 rounded-xl transition outline-none"
                      onClick={() => setOpen(false)}
                    >
                      <QuestionMarkCircle className="size-5" />
                      <div className="flex items-center">Documentation</div>
                    </a>
                  </DropdownMenuPrimitive.Item>
                </>
              )}

              <DropdownMenuPrimitive.Item
                className="flex gap-3 items-center py-1.5 px-3 text-sm select-none w-full hover:bg-gray-50 dark:hover:bg-gray-800 rounded-xl transition cursor-pointer outline-none"
                onSelect={() => {
                  setOpen(false);
                  setShowShortcuts(true);
                  if (mobile) {
                    setShowSidebar(false);
                  }
                }}
              >
                <Keyboard className="size-5" />
                <div className="flex items-center">Keyboard shortcuts</div>
              </DropdownMenuPrimitive.Item>
            </>
          )}

          <DropdownMenuPrimitive.Separator className="border-gray-50 dark:border-gray-800 my-1" />

          <DropdownMenuPrimitive.Item
            className="flex rounded-xl py-1.5 px-3 w-full hover:bg-gray-50 dark:hover:bg-gray-800 transition cursor-pointer outline-none"
            onSelect={handleSignOut}
          >
            <div className="self-center mr-3">
              <SignOut className="w-5 h-5" strokeWidth={1.5} />
            </div>
            <div className="self-center truncate">Sign Out</div>
          </DropdownMenuPrimitive.Item>

          {usage?.user_ids && usage.user_ids.length > 0 && (
            <>
              <DropdownMenuPrimitive.Separator className="border-gray-50 dark:border-gray-800 my-1" />
              <Tooltip
                content={
                  usage?.model_ids && usage.model_ids.length > 0
                    ? `Running: ${usage.model_ids.join(', ')} ✨`
                    : ''
                }
              >
                <div className="flex rounded-xl py-1 px-3 text-xs gap-2.5 items-center">
                  <div className="flex items-center">
                    <span className="relative flex size-2">
                      <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75" />
                      <span className="relative inline-flex rounded-full size-2 bg-green-500" />
                    </span>
                  </div>
                  <div>
                    <span>Active Users:</span>
                    <span className="font-semibold"> {usage.user_ids.length}</span>
                  </div>
                </div>
              </Tooltip>
            </>
          )}
        </DropdownMenuPrimitive.Content>
      </DropdownMenuPrimitive.Portal>
    </DropdownMenuPrimitive.Root>
  );
}

// src/lib/components/layout/Sidebar/UserMenu.svelte
<script lang="ts">
	import { DropdownMenu } from 'bits-ui';
	import { createEventDispatcher, tick } from 'svelte';

	import { fade } from 'svelte/transition';

	import { getUsage } from '$lib/apis';
	import { userSignOut } from '$lib/apis/auths';

	import { showSettings, mobile, showSidebar, showShortcuts, user } from '$lib/stores';

	import Tooltip from '$lib/components/common/Tooltip.svelte';
	import ArchiveBox from '$lib/components/icons/ArchiveBox.svelte';
	import QuestionMarkCircle from '$lib/components/icons/QuestionMarkCircle.svelte';
	import Map from '$lib/components/icons/Map.svelte';
	import Keyboard from '$lib/components/icons/Keyboard.svelte';
	import ShortcutsModal from '$lib/components/chat/ShortcutsModal.svelte';
	import Settings from '$lib/components/icons/Settings.svelte';
	import UserGroup from '$lib/components/icons/UserGroup.svelte';
	import SignOut from '$lib/components/icons/SignOut.svelte';
	export let show = false;
	export let role = '';
	export let help = false;
	export let className = 'max-w-[240px]';

	const dispatch = createEventDispatcher();

	let usage = null;
	const getUsageInfo = async () => {
		const res = await getUsage(localStorage.token).catch((error) => {
			console.error('Error fetching usage info:', error);
		});

		if (res) {
			usage = res;
		} else {
			usage = null;
		}
	};

	$: if (show) {
		getUsageInfo();
	}
</script>

<ShortcutsModal bind:show={$showShortcuts} />

<!-- svelte-ignore a11y-no-static-element-interactions -->
<DropdownMenu.Root
	bind:open={show}
	onOpenChange={(state) => {
		dispatch('change', state);
	}}
>
	<DropdownMenu.Trigger>
		<slot />
	</DropdownMenu.Trigger>

	<slot name="content">
		<DropdownMenu.Content
			class="w-full {className}  rounded-2xl px-1 py-1  border border-gray-100  dark:border-gray-800 z-50 bg-white dark:bg-gray-850 dark:text-white shadow-lg text-sm"
			sideOffset={4}
			side="top"
			align="end"
			transition={(e) => fade(e, { duration: 100 })}
		>
			<DropdownMenu.Item
				class="flex rounded-xl py-1.5 px-3 w-full hover:bg-gray-50 dark:hover:bg-gray-800 transition cursor-pointer"
				on:click={async () => {
					show = false;

					await showSettings.set(true);

					if ($mobile) {
						await tick();
						showSidebar.set(false);
					}
				}}
			>
				<div class=" self-center mr-3">
					<Settings className="w-5 h-5" strokeWidth="1.5" />
				</div>
				<div class=" self-center truncate">{'Settings'}</div>
			</DropdownMenu.Item>

			<DropdownMenu.Item
				class="flex rounded-xl py-1.5 px-3 w-full hover:bg-gray-50 dark:hover:bg-gray-800 transition cursor-pointer"
				on:click={async () => {
					show = false;

					dispatch('show', 'archived-chat');

					if ($mobile) {
						await tick();

						showSidebar.set(false);
					}
				}}
			>
				<div class=" self-center mr-3">
					<ArchiveBox className="size-5" strokeWidth="1.5" />
				</div>
				<div class=" self-center truncate">{'Archived Chats'}</div>
			</DropdownMenu.Item>

			{#if role === 'admin'}
				<DropdownMenu.Item
					as="a"
					href="/admin"
					class="flex rounded-xl py-1.5 px-3 w-full hover:bg-gray-50 dark:hover:bg-gray-800 transition select-none"
					on:click={async () => {
						show = false;
						if ($mobile) {
							await tick();
							showSidebar.set(false);
						}
					}}
				>
					<div class=" self-center mr-3">
						<UserGroup className="w-5 h-5" strokeWidth="1.5" />
					</div>
					<div class=" self-center truncate">{'Admin Panel'}</div>
				</DropdownMenu.Item>
			{/if}

			{#if help}
				<hr class=" border-gray-50 dark:border-gray-800 my-1 p-0" />

				<!-- {'Help'} -->

				{#if $user?.role === 'admin'}
					<DropdownMenu.Item
						as="a"
						target="_blank"
						class="flex gap-3 items-center py-1.5 px-3 text-sm select-none w-full cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-800 rounded-xl transition"
						id="chat-share-button"
						on:click={() => {
							show = false;
						}}
						href="https://docs.openwebui.com"
					>
						<QuestionMarkCircle className="size-5" />
						<div class="flex items-center">{'Documentation'}</div>
					</DropdownMenu.Item>

					<!-- Releases -->
					<DropdownMenu.Item
						as="a"
						target="_blank"
						class="flex gap-3 items-center py-1.5 px-3 text-sm select-none w-full cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-800 rounded-xl transition"
						id="chat-share-button"
						on:click={() => {
							show = false;
						}}
						href="https://github.com/open-webui/open-webui/releases"
					>
						<Map className="size-5" />
						<div class="flex items-center">{'Releases'}</div>
					</DropdownMenu.Item>
				{/if}

				<DropdownMenu.Item
					class="flex gap-3 items-center py-1.5 px-3 text-sm select-none w-full  hover:bg-gray-50 dark:hover:bg-gray-800 rounded-xl transition cursor-pointer"
					id="chat-share-button"
					on:click={async () => {
						show = false;
						showShortcuts.set(!$showShortcuts);

						if ($mobile) {
							await tick();
							showSidebar.set(false);
						}
					}}
				>
					<Keyboard className="size-5" />
					<div class="flex items-center">{'Keyboard shortcuts'}</div>
				</DropdownMenu.Item>
			{/if}

			<hr class=" border-gray-50 dark:border-gray-800 my-1 p-0" />

			<DropdownMenu.Item
				class="flex rounded-xl py-1.5 px-3 w-full hover:bg-gray-50 dark:hover:bg-gray-800 transition"
				on:click={async () => {
					const res = await userSignOut();
					user.set(null);
					localStorage.removeItem('token');

					location.href = res?.redirect_url ?? '/auth';
					show = false;
				}}
			>
				<div class=" self-center mr-3">
					<SignOut className="w-5 h-5" strokeWidth="1.5" />
				</div>
				<div class=" self-center truncate">{'Sign Out'}</div>
			</DropdownMenu.Item>

			{#if usage}
				{#if usage?.user_ids?.length > 0}
					<hr class=" border-gray-50 dark:border-gray-800 my-1 p-0" />

					<Tooltip
						content={usage?.model_ids && usage?.model_ids.length > 0
							? `${'Running'}: ${usage.model_ids.join(', ')} ✨`
							: ''}
					>
						<div
							class="flex rounded-xl py-1 px-3 text-xs gap-2.5 items-center"
							on:mouseenter={() => {
								getUsageInfo();
							}}
						>
							<div class=" flex items-center">
								<span class="relative flex size-2">
									<span
										class="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"
									/>
									<span class="relative inline-flex rounded-full size-2 bg-green-500" />
								</span>
							</div>

							<div class=" ">
								<span class="">
									{'Active Users'}:
								</span>
								<span class=" font-semibold">
									{usage?.user_ids?.length}
								</span>
							</div>
						</div>
					</Tooltip>
				{/if}
			{/if}

			<!-- <DropdownMenu.Item class="flex items-center py-1.5 px-3 text-sm ">
				<div class="flex items-center">Profile</div>
			</DropdownMenu.Item> -->
		</DropdownMenu.Content>
	</slot>
</DropdownMenu.Root>
