// src/lib/components/common/Dropdown.svelte
<script lang="ts">
	import { DropdownMenu } from 'bits-ui';
	import { createEventDispatcher } from 'svelte';
	import { flyAndScale } from '$lib/utils/transitions';

	export let show = false;
	export let side = 'bottom';
	export let align = 'start';
	export let closeOnOutsideClick = true;

	const dispatch = createEventDispatcher();
</script>

<DropdownMenu.Root
	bind:open={show}
	closeFocus={false}
	{closeOnOutsideClick}
	onOpenChange={(state) => {
		dispatch('change', state);
	}}
	typeahead={false}
>
	<DropdownMenu.Trigger>
		<slot />
	</DropdownMenu.Trigger>

	<slot name="content">
		<DropdownMenu.Content
			class="w-full max-w-[130px] rounded-lg p-1 border border-gray-900 z-50 bg-gray-850 text-white"
			sideOffset={8}
			{side}
			{align}
			transition={flyAndScale}
		>
			<DropdownMenu.Item class="flex items-center px-3 py-2 text-sm  font-medium">
				<div class="flex items-center">{'Profile'}</div>
			</DropdownMenu.Item>

			<DropdownMenu.Item class="flex items-center px-3 py-2 text-sm  font-medium">
				<div class="flex items-center">{'Profile'}</div>
			</DropdownMenu.Item>

			<DropdownMenu.Item class="flex items-center px-3 py-2 text-sm  font-medium">
				<div class="flex items-center">{'Profile'}</div>
			</DropdownMenu.Item>
		</DropdownMenu.Content>
	</slot>
</DropdownMenu.Root>

// next-app/src/components/common/Dropdown.tsx
'use client';

import * as DropdownMenuPrimitive from '@radix-ui/react-dropdown-menu';
import { ReactNode } from 'react';

interface DropdownProps {
	open?: boolean;
	onOpenChange?: (open: boolean) => void;
	side?: 'top' | 'right' | 'bottom' | 'left';
	align?: 'start' | 'center' | 'end';
	trigger: ReactNode;
	children: ReactNode;
	className?: string;
	sideOffset?: number;
}

export function Dropdown({
	open,
	onOpenChange,
	side = 'bottom',
	align = 'start',
	trigger,
	children,
	className = 'w-full max-w-[200px] rounded-lg p-1 border border-gray-300 dark:border-gray-700 z-50 bg-white dark:bg-gray-850 text-gray-900 dark:text-white shadow-lg',
	sideOffset = 8
}: DropdownProps) {
	return (
		<DropdownMenuPrimitive.Root open={open} onOpenChange={onOpenChange}>
			<DropdownMenuPrimitive.Trigger asChild>{trigger}</DropdownMenuPrimitive.Trigger>
			<DropdownMenuPrimitive.Portal>
				<DropdownMenuPrimitive.Content
					className={className}
					sideOffset={sideOffset}
					side={side}
					align={align}
				>
					{children}
				</DropdownMenuPrimitive.Content>
			</DropdownMenuPrimitive.Portal>
		</DropdownMenuPrimitive.Root>
	);
}

interface DropdownItemProps {
	children: ReactNode;
	onClick?: () => void;
	className?: string;
	disabled?: boolean;
}

export function DropdownItem({
	children,
	onClick,
	className = 'flex items-center px-3 py-2 text-sm font-medium cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-800 outline-none',
	disabled = false
}: DropdownItemProps) {
	return (
		<DropdownMenuPrimitive.Item className={className} onClick={onClick} disabled={disabled}>
			{children}
		</DropdownMenuPrimitive.Item>
	);
}

interface DropdownSeparatorProps {
	className?: string;
}

export function DropdownSeparator({
	className = 'h-px bg-gray-200 dark:bg-gray-700 my-1'
}: DropdownSeparatorProps) {
	return <DropdownMenuPrimitive.Separator className={className} />;
}

interface DropdownLabelProps {
	children: ReactNode;
	className?: string;
}

export function DropdownLabel({
	children,
	className = 'px-3 py-1.5 text-xs font-semibold text-gray-500 dark:text-gray-400'
}: DropdownLabelProps) {
	return (
		<DropdownMenuPrimitive.Label className={className}>{children}</DropdownMenuPrimitive.Label>
	);
}
