// src/lib/components/common/Pagination.svelte
<script lang="ts">
	import { Pagination } from 'bits-ui';

	import ChevronLeft from '../icons/ChevronLeft.svelte';
	import ChevronRight from '../icons/ChevronRight.svelte';

	export let page = 0;
	export let count = 0;
	export let perPage = 20;
</script>

<div class="flex justify-center">
	<Pagination.Root bind:page {count} {perPage} let:pages>
		<div class="my-2 flex items-center">
			<Pagination.PrevButton
				class="mr-[25px] inline-flex size-8 items-center justify-center rounded-[9px] bg-transparent hover:bg-gray-50 dark:hover:bg-gray-850 active:scale-98 disabled:cursor-not-allowed disabled:text-gray-400 dark:disabled:text-gray-700 hover:disabled:bg-transparent dark:hover:disabled:bg-transparent"
			>
				<ChevronLeft className="size-4" strokeWidth="2" />
			</Pagination.PrevButton>
			<div class="flex items-center gap-2.5">
				{#each pages as page (page.key)}
					{#if page.type === 'ellipsis'}
						<div class="text-sm font-medium text-foreground-alt">...</div>
					{:else}
						<Pagination.Page
							{page}
							class="inline-flex size-8 items-center justify-center rounded-[9px] bg-transparent hover:bg-gray-50 dark:hover:bg-gray-850 text-sm font-medium hover:bg-dark-10 active:scale-98 disabled:cursor-not-allowed disabled:opacity-50 hover:disabled:bg-transparent data-selected:bg-gray-50 data-selected:text-gray-700 data-selected:hover:bg-gray-100 dark:data-selected:bg-gray-850 dark:data-selected:text-gray-50 dark:data-selected:hover:bg-gray-800 transition"
						>
							{page.value}
						</Pagination.Page>
					{/if}
				{/each}
			</div>
			<Pagination.NextButton
				class="ml-[25px]  inline-flex size-8 items-center justify-center rounded-[9px] bg-transparent hover:bg-gray-50 dark:hover:bg-gray-850 active:scale-98 disabled:cursor-not-allowed disabled:text-gray-400 dark:disabled:text-gray-700 hover:disabled:bg-transparent dark:hover:disabled:bg-transparent"
			>
				<ChevronRight className="size-4" strokeWidth="2" />
			</Pagination.NextButton>
		</div>
	</Pagination.Root>
</div>

// next-app/src/components/common/Pagination.tsx
'use client';

import { useMemo } from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';

interface PaginationProps {
  page: number;
  count: number;
  perPage?: number;
  onPageChange: (page: number) => void;
}

export function Pagination({
  page,
  count,
  perPage = 20,
  onPageChange,
}: PaginationProps) {
  const totalPages = Math.ceil(count / perPage);

  const pages = useMemo(() => {
    const result: Array<{ type: 'page' | 'ellipsis'; value: number; key: string }> = [];

    if (totalPages <= 7) {
      for (let i = 1; i <= totalPages; i++) {
        result.push({ type: 'page', value: i, key: `page-${i}` });
      }
    } else {
      result.push({ type: 'page', value: 1, key: 'page-1' });

      if (page > 3) {
        result.push({ type: 'ellipsis', value: 0, key: 'ellipsis-start' });
      }

      const start = Math.max(2, page - 1);
      const end = Math.min(totalPages - 1, page + 1);

      for (let i = start; i <= end; i++) {
        result.push({ type: 'page', value: i, key: `page-${i}` });
      }

      if (page < totalPages - 2) {
        result.push({ type: 'ellipsis', value: 0, key: 'ellipsis-end' });
      }

      result.push({ type: 'page', value: totalPages, key: `page-${totalPages}` });
    }

    return result;
  }, [page, totalPages]);

  if (totalPages <= 1) return null;

  return (
    <div className="flex justify-center">
      <div className="my-2 flex items-center">
        <button
          className="mr-[25px] inline-flex size-8 items-center justify-center rounded-[9px] bg-transparent hover:bg-gray-50 dark:hover:bg-gray-850 active:scale-98 disabled:cursor-not-allowed disabled:text-gray-400 dark:disabled:text-gray-700 hover:disabled:bg-transparent dark:hover:disabled:bg-transparent"
          onClick={() => onPageChange(page - 1)}
          disabled={page <= 1}
        >
          <ChevronLeft className="size-4" strokeWidth={2} />
        </button>

        <div className="flex items-center gap-2.5">
          {pages.map((p) =>
            p.type === 'ellipsis' ? (
              <div
                key={p.key}
                className="text-sm font-medium text-gray-500 dark:text-gray-400"
              >
                ...
              </div>
            ) : (
              <button
                key={p.key}
                className={`inline-flex size-8 items-center justify-center rounded-[9px] bg-transparent hover:bg-gray-50 dark:hover:bg-gray-850 text-sm font-medium active:scale-98 disabled:cursor-not-allowed disabled:opacity-50 hover:disabled:bg-transparent transition ${
                  p.value === page
                    ? 'bg-gray-50 text-gray-700 hover:bg-gray-100 dark:bg-gray-850 dark:text-gray-50 dark:hover:bg-gray-800'
                    : ''
                }`}
                onClick={() => onPageChange(p.value)}
              >
                {p.value}
              </button>
            )
          )}
        </div>

        <button
          className="ml-[25px] inline-flex size-8 items-center justify-center rounded-[9px] bg-transparent hover:bg-gray-50 dark:hover:bg-gray-850 active:scale-98 disabled:cursor-not-allowed disabled:text-gray-400 dark:disabled:text-gray-700 hover:disabled:bg-transparent dark:hover:disabled:bg-transparent"
          onClick={() => onPageChange(page + 1)}
          disabled={page >= totalPages}
        >
          <ChevronRight className="size-4" strokeWidth={2} />
        </button>
      </div>
    </div>
  );
}
