// src/routes/(app)/workspace/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { user } from '$lib/stores';
	import { onMount } from 'svelte';

	onMount(() => {
		if ($user?.role !== 'admin') {
			if ($user?.permissions?.workspace?.models) {
				goto('/workspace/models');
			} else if ($user?.permissions?.workspace?.knowledge) {
				goto('/workspace/knowledge');
			} else if ($user?.permissions?.workspace?.prompts) {
				goto('/workspace/prompts');
			} else {
				goto('/');
			}
		} else {
			goto('/workspace/models');
		}
	});
</script>

// next-app/src/app/(app)/workspace/page.tsx
'use client';

import { useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useAppStore } from '@/store';

export default function WorkspacePage() {
  const router = useRouter();
  const user = useAppStore((s) => s.user);

  useEffect(() => {
    if (user?.role !== 'admin') {
      if (user?.permissions?.workspace?.models) {
        router.push('/workspace/models');
      } else if (user?.permissions?.workspace?.knowledge) {
        router.push('/workspace/knowledge');
      } else if (user?.permissions?.workspace?.prompts) {
        router.push('/workspace/prompts');
      } else {
        router.push('/');
      }
    } else {
      router.push('/workspace/models');
    }
  }, [user, router]);

  return null;
}
