// src/lib/components/admin/Users/Groups/Users.svelte
<script lang="ts">
	import dayjs from 'dayjs';
	import relativeTime from 'dayjs/plugin/relativeTime';
	import localizedFormat from 'dayjs/plugin/localizedFormat';
	dayjs.extend(relativeTime);
	dayjs.extend(localizedFormat);

	import { getUsers } from '$lib/apis/users';
	import { toast } from 'svelte-sonner';

	import { addUserToGroup, removeUserFromGroup } from '$lib/apis/groups';
	import { WEBUI_API_BASE_URL } from '$lib/constants';

	import Tooltip from '$lib/components/common/Tooltip.svelte';
	import Checkbox from '$lib/components/common/Checkbox.svelte';
	import Badge from '$lib/components/common/Badge.svelte';
	import Search from '$lib/components/icons/Search.svelte';
	import Pagination from '$lib/components/common/Pagination.svelte';
	import ChevronDown from '$lib/components/icons/ChevronDown.svelte';
	import ChevronUp from '$lib/components/icons/ChevronUp.svelte';
	import Spinner from '$lib/components/common/Spinner.svelte';

	export let groupId: string;
	export let userCount = 0;

	let users = null;
	let total = null;

	let query = '';
	let orderBy = `group_id:${groupId}`; // default sort key
	let direction = 'desc'; // default sort order

	let page = 1;

	const setSortKey = (key) => {
		if (orderBy === key) {
			direction = direction === 'asc' ? 'desc' : 'asc';
		} else {
			orderBy = key;
			direction = 'asc';
		}
	};

	const getUserList = async () => {
		try {
			const res = await getUsers(localStorage.token, query, orderBy, direction, page).catch(
				(error) => {
					toast.error(`${error}`);
					return null;
				}
			);

			if (res) {
				users = res.users;
				total = res.total;
			}
		} catch (err) {
			console.error(err);
		}
	};

	const toggleMember = async (userId, state) => {
		if (state === 'checked') {
			await addUserToGroup(localStorage.token, groupId, [userId]).catch((error) => {
				toast.error(`${error}`);
				return null;
			});
		} else {
			await removeUserFromGroup(localStorage.token, groupId, [userId]).catch((error) => {
				toast.error(`${error}`);
				return null;
			});
		}

		page = 1;
		getUserList();
	};

	$: if (page !== null && query !== null && orderBy !== null && direction !== null) {
		getUserList();
	}

	$: if (query) {
		page = 1;
	}
</script>

<div class=" max-h-full h-full w-full flex flex-col overflow-y-hidden">
	<div class="w-full h-fit mb-1.5">
		<div class="flex flex-1 h-fit">
			<div class=" self-center mr-3">
				<Search />
			</div>
			<input
				class=" w-full text-sm pr-4 rounded-r-xl outline-hidden bg-transparent"
				bind:value={query}
				placeholder={'Search'}
			/>
		</div>
	</div>

	{#if users === null || total === null}
		<div class="my-10">
			<Spinner className="size-5" />
		</div>
	{:else}
		{#if users.length > 0}
			<div class="scrollbar-hidden relative whitespace-nowrap overflow-x-auto max-w-full">
				<table
					class="w-full text-sm text-left text-gray-500 dark:text-gray-400 table-auto max-w-full"
				>
					<thead class="text-xs text-gray-800 uppercase bg-transparent dark:text-gray-200">
						<tr class=" border-b-[1.5px] border-gray-50 dark:border-gray-850">
							<th
								scope="col"
								class="px-2.5 py-2 cursor-pointer text-left w-8"
								on:click={() => setSortKey(`group_id:${groupId}`)}
							>
								<div class="flex gap-1.5 items-center">
									{'MBR'}

									{#if orderBy === `group_id:${groupId}`}
										<span class="font-normal"
											>{#if direction === 'asc'}
												<ChevronUp className="size-2" />
											{:else}
												<ChevronDown className="size-2" />
											{/if}
										</span>
									{:else}
										<span class="invisible">
											<ChevronUp className="size-2" />
										</span>
									{/if}
								</div>
							</th>

							<th
								scope="col"
								class="px-2.5 py-2 cursor-pointer select-none"
								on:click={() => setSortKey('role')}
							>
								<div class="flex gap-1.5 items-center">
									{'Role'}

									{#if orderBy === 'role'}
										<span class="font-normal"
											>{#if direction === 'asc'}
												<ChevronUp className="size-2" />
											{:else}
												<ChevronDown className="size-2" />
											{/if}
										</span>
									{:else}
										<span class="invisible">
											<ChevronUp className="size-2" />
										</span>
									{/if}
								</div>
							</th>
							<th
								scope="col"
								class="px-2.5 py-2 cursor-pointer select-none"
								on:click={() => setSortKey('name')}
							>
								<div class="flex gap-1.5 items-center">
									{'Name'}

									{#if orderBy === 'name'}
										<span class="font-normal"
											>{#if direction === 'asc'}
												<ChevronUp className="size-2" />
											{:else}
												<ChevronDown className="size-2" />
											{/if}
										</span>
									{:else}
										<span class="invisible">
											<ChevronUp className="size-2" />
										</span>
									{/if}
								</div>
							</th>

							<th
								scope="col"
								class="px-2.5 py-2 cursor-pointer select-none"
								on:click={() => setSortKey('last_active_at')}
							>
								<div class="flex gap-1.5 items-center">
									{'Last Active'}

									{#if orderBy === 'last_active_at'}
										<span class="font-normal"
											>{#if direction === 'asc'}
												<ChevronUp className="size-2" />
											{:else}
												<ChevronDown className="size-2" />
											{/if}
										</span>
									{:else}
										<span class="invisible">
											<ChevronUp className="size-2" />
										</span>
									{/if}
								</div>
							</th>
						</tr>
					</thead>
					<tbody class="">
						{#each users as user, userIdx (user?.id ?? userIdx)}
							<tr class="bg-white dark:bg-gray-900 dark:border-gray-850 text-xs">
								<td class=" px-3 py-1 w-8">
									<div class="flex w-full justify-center">
										<Checkbox
											state={(user?.group_ids ?? []).includes(groupId) ? 'checked' : 'unchecked'}
											on:change={(e) => {
												toggleMember(user.id, e.detail);
											}}
										/>
									</div>
								</td>
								<td class="px-3 py-1 min-w-[7rem] w-28">
									<div class=" translate-y-0.5">
										<Badge
											type={user.role === 'admin'
												? 'info'
												: user.role === 'user'
													? 'success'
													: 'muted'}
											content={user.role}
										/>
									</div>
								</td>
								<td class="px-3 py-1 font-medium text-gray-900 dark:text-white max-w-48">
									<Tooltip content={user.email} placement="top-start">
										<div class="flex items-center">
											<img
												class="rounded-full w-6 h-6 object-cover mr-2.5 flex-shrink-0"
												src={`${WEBUI_API_BASE_URL}/users/${user.id}/profile/image`}
												alt="user"
											/>

											<div class="font-medium truncate">{user.name}</div>
										</div>
									</Tooltip>
								</td>

								<td class=" px-3 py-1">
									{dayjs(user.last_active_at * 1000).fromNow()}
								</td>
							</tr>
						{/each}
					</tbody>
				</table>
			</div>
		{:else}
			<div class="text-gray-500 text-xs text-center py-2 px-10">
				{'No users were found.'}
			</div>
		{/if}

		{#if total > 30}
			<Pagination bind:page count={total} perPage={30} />
		{/if}
	{/if}
</div>

// next-app/src/app/(app)/admin/users/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { WEBUI_API_BASE_URL } from '@/lib/constants';
import { Spinner } from '@/components/common/Spinner';
import { Plus, Pencil, Trash2, User as UserIcon, Shield, ShieldCheck } from 'lucide-react';

interface User {
	id: string;
	email: string;
	name: string;
	role: 'admin' | 'user' | 'pending';
	profile_image_url?: string;
	created_at?: string;
	last_active_at?: string;
}

export default function UsersPage() {
	const [loading, setLoading] = useState(true);
	const [users, setUsers] = useState<User[]>([]);
	const [searchQuery, setSearchQuery] = useState('');

	useEffect(() => {
		const loadUsers = async () => {
			const token = localStorage.getItem('token');
			if (!token) return;

			try {
				const res = await fetch(`${WEBUI_API_BASE_URL}/users`, {
					headers: { Authorization: `Bearer ${token}` }
				});

				if (res.ok) {
					const data = await res.json();
					setUsers(data);
				}
			} catch (error) {
				console.error('Failed to load users:', error);
				setUsers([]);
			} finally {
				setLoading(false);
			}
		};

		loadUsers();
	}, []);

	const filteredUsers = users.filter(
		(user) =>
			user.name?.toLowerCase().includes(searchQuery.toLowerCase()) ||
			user.email?.toLowerCase().includes(searchQuery.toLowerCase())
	);

	const getRoleIcon = (role: string) => {
		switch (role) {
			case 'admin':
				return <ShieldCheck className="size-4 text-blue-500" />;
			case 'pending':
				return <Shield className="size-4 text-yellow-500" />;
			default:
				return <UserIcon className="size-4 text-gray-500" />;
		}
	};

	if (loading) {
		return (
			<div className="flex items-center justify-center h-64">
				<Spinner className="size-8" />
			</div>
		);
	}

	return (
		<div className="p-4">
			<div className="flex items-center justify-between mb-4">
				<h1 className="text-2xl font-semibold">Users</h1>
				<button className="flex items-center gap-2 px-4 py-2 bg-black dark:bg-white text-white dark:text-black rounded-lg hover:opacity-80 transition">
					<Plus className="size-4" />
					Add User
				</button>
			</div>

			<div className="mb-4">
				<input
					type="text"
					placeholder="Search users..."
					value={searchQuery}
					onChange={(e) => setSearchQuery(e.target.value)}
					className="w-full max-w-md px-4 py-2 border border-gray-200 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500"
				/>
			</div>

			<div className="overflow-x-auto">
				<table className="w-full">
					<thead>
						<tr className="border-b border-gray-200 dark:border-gray-700">
							<th className="text-left py-3 px-4 font-medium text-gray-500 dark:text-gray-400">
								User
							</th>
							<th className="text-left py-3 px-4 font-medium text-gray-500 dark:text-gray-400">
								Role
							</th>
							<th className="text-left py-3 px-4 font-medium text-gray-500 dark:text-gray-400">
								Created
							</th>
							<th className="text-right py-3 px-4 font-medium text-gray-500 dark:text-gray-400">
								Actions
							</th>
						</tr>
					</thead>
					<tbody>
						{filteredUsers.map((user) => (
							<tr
								key={user.id}
								className="border-b border-gray-100 dark:border-gray-800 hover:bg-gray-50 dark:hover:bg-gray-800/50"
							>
								<td className="py-3 px-4">
									<div className="flex items-center gap-3">
										<div className="w-8 h-8 rounded-full bg-gray-200 dark:bg-gray-700 flex items-center justify-center overflow-hidden">
											{user.profile_image_url ? (
												<img
													src={user.profile_image_url}
													alt={user.name}
													className="w-full h-full object-cover"
												/>
											) : (
												<span className="text-sm font-medium">
													{user.name?.charAt(0)?.toUpperCase() || '?'}
												</span>
											)}
										</div>
										<div>
											<div className="font-medium">{user.name}</div>
											<div className="text-sm text-gray-500 dark:text-gray-400">{user.email}</div>
										</div>
									</div>
								</td>
								<td className="py-3 px-4">
									<div className="flex items-center gap-2">
										{getRoleIcon(user.role)}
										<span className="capitalize">{user.role}</span>
									</div>
								</td>
								<td className="py-3 px-4 text-gray-500 dark:text-gray-400">
									{user.created_at ? new Date(user.created_at).toLocaleDateString() : '-'}
								</td>
								<td className="py-3 px-4">
									<div className="flex items-center justify-end gap-2">
										<button className="p-2 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition">
											<Pencil className="size-4" />
										</button>
										<button className="p-2 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition text-red-500">
											<Trash2 className="size-4" />
										</button>
									</div>
								</td>
							</tr>
						))}
					</tbody>
				</table>
				{filteredUsers.length === 0 && (
					<div className="text-center py-8 text-gray-500 dark:text-gray-400">No users found</div>
				)}
			</div>
		</div>
	);
}
