// next-app/src/components/chat/Messages/UserMessage.tsx
'use client';

import { useState, useRef, useEffect, useCallback } from 'react';
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';
import localizedFormat from 'dayjs/plugin/localizedFormat';
import { ChevronLeft, ChevronRight, Pencil, Copy, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { useAppStore } from '@/store';
import { WEBUI_API_BASE_URL } from '@/lib/constants';
import { copyToClipboard } from '@/lib/utils';
import { Markdown } from './Markdown';
import { ProfileImage } from './ProfileImage';
import { Name } from './Name';
import { Tooltip } from '@/components/common/Tooltip';
import { ConfirmDialog } from '@/components/common/ConfirmDialog';
import { Image } from '@/components/common/Image';

dayjs.extend(relativeTime);
dayjs.extend(localizedFormat);

interface HistoryMessage {
	id: string;
	role: string;
	content: string;
	parentId: string | null;
	childrenIds: string[];
	files?: { type: string; url: string; name?: string; size?: number }[];
	timestamp?: number;
	user?: string;
}

interface History {
	messages: Record<string, HistoryMessage>;
	currentId: string | null;
}

interface UserMessageProps {
	user: { id: string; name: string; role?: string };
	chatId: string;
	history: History;
	messageId: string;
	siblings: string[];
	gotoMessage: (message: HistoryMessage, idx: number) => void;
	showPreviousMessage: (message: HistoryMessage) => void;
	showNextMessage: (message: HistoryMessage) => void;
	editMessage: (
		messageId: string,
		data: { content: string; files?: unknown[] },
		submit?: boolean
	) => void;
	deleteMessage: (messageId: string) => void;
	isFirstMessage?: boolean;
	readOnly?: boolean;
	editCodeBlock?: boolean;
	topPadding?: boolean;
}

export function UserMessage({
	user,
	chatId,
	history,
	messageId,
	siblings,
	gotoMessage,
	showPreviousMessage,
	showNextMessage,
	editMessage,
	deleteMessage,
	isFirstMessage = false,
	readOnly = false,
	editCodeBlock = true,
	topPadding = false
}: UserMessageProps) {
	const settings = useAppStore((s) => s.settings);
	const currentUser = useAppStore((s) => s.user);

	const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
	const [messageIndexEdit, setMessageIndexEdit] = useState(false);
	const [edit, setEdit] = useState(false);
	const [editedContent, setEditedContent] = useState('');
	const [editedFiles, setEditedFiles] = useState<{ type: string; url: string; name?: string }[]>(
		[]
	);

	const textareaRef = useRef<HTMLTextAreaElement>(null);

	const message = history.messages[messageId];

	useEffect(() => {
		if (edit && textareaRef.current) {
			textareaRef.current.style.height = '';
			textareaRef.current.style.height = `${textareaRef.current.scrollHeight}px`;
			textareaRef.current.focus();
		}
	}, [edit]);

	const handleCopyToClipboard = useCallback(async (text: string) => {
		const res = await copyToClipboard(text);
		if (res) {
			toast.success('Copied to clipboard');
		}
	}, []);

	const handleEditMessage = useCallback(() => {
		setEdit(true);
		setEditedContent(message?.content ?? '');
		setEditedFiles(message?.files ?? []);
	}, [message]);

	const handleEditConfirm = useCallback(
		(submit = true) => {
			if (!editedContent && (editedFiles ?? []).length === 0) {
				toast.error('Please enter a message or attach a file.');
				return;
			}

			editMessage(message.id, { content: editedContent, files: editedFiles }, submit);
			setEdit(false);
			setEditedContent('');
			setEditedFiles([]);
		},
		[editedContent, editedFiles, message?.id, editMessage]
	);

	const cancelEdit = useCallback(() => {
		setEdit(false);
		setEditedContent('');
		setEditedFiles([]);
	}, []);

	const chatBubble = settings?.chatBubble ?? true;
	const highContrastMode = settings?.highContrastMode ?? false;
	const siblingIndex = siblings.indexOf(message?.id);

	if (!message) return null;

	return (
		<>
			<ConfirmDialog
				show={showDeleteConfirm}
				onClose={() => setShowDeleteConfirm(false)}
				title="Delete message?"
				onConfirm={() => deleteMessage(message.id)}
			/>

			<div
				className="flex w-full user-message group"
				dir={settings?.chatDirection}
				id={`message-${message.id}`}
			>
				{!chatBubble && (
					<div className="shrink-0 ltr:mr-3 rtl:ml-3 mt-1">
						<ProfileImage
							src={`${WEBUI_API_BASE_URL}/users/${user.id}/profile/image`}
							className="size-8 user-message-profile-image"
						/>
					</div>
				)}

				<div className="flex-auto w-0 max-w-full pl-1">
					{!chatBubble ? (
						<div>
							<Name>
								{message.user ? (
									<>
										You
										<span className="text-gray-500 text-sm font-medium">{message.user}</span>
									</>
								) : settings?.showUsername || currentUser?.name !== user.name ? (
									user.name
								) : (
									'You'
								)}

								{message.timestamp && (
									<div
										className={`self-center text-xs font-medium first-letter:capitalize ml-0.5 translate-y-[1px] ${
											highContrastMode
												? 'dark:text-gray-900 text-gray-100'
												: 'invisible group-hover:visible transition'
										}`}
									>
										<Tooltip content={dayjs(message.timestamp * 1000).format('LLLL')}>
											<span className="line-clamp-1">
												{dayjs(message.timestamp * 1000).fromNow()}
											</span>
										</Tooltip>
									</div>
								)}
							</Name>
						</div>
					) : (
						message.timestamp && (
							<div className="flex justify-end pr-2 text-xs">
								<div
									className={`text-[0.65rem] font-medium first-letter:capitalize mb-0.5 ${
										highContrastMode
											? 'dark:text-gray-100 text-gray-900'
											: 'invisible group-hover:visible transition text-gray-400'
									}`}
								>
									<Tooltip content={dayjs(message.timestamp * 1000).format('LLLL')}>
										<span className="line-clamp-1">
											{dayjs(message.timestamp * 1000).fromNow()}
										</span>
									</Tooltip>
								</div>
							</div>
						)
					)}

					<div className={`chat-${message.role} w-full min-w-full markdown-prose`}>
						{!edit && message.files && (
							<div className="mb-1 w-full flex flex-col justify-end overflow-x-auto gap-1 flex-wrap">
								{message.files.map((file, idx) => (
									<div key={idx} className={chatBubble ? 'self-end' : ''}>
										{file.type === 'image' ? (
											<Image src={file.url} imageClassName="max-h-96 rounded-lg" />
										) : (
											<div className="flex items-center gap-2 p-2 bg-gray-100 dark:bg-gray-800 rounded-lg">
												<span className="text-sm">{file.name || 'File'}</span>
											</div>
										)}
									</div>
								))}
							</div>
						)}

						{edit ? (
							<div className="w-full bg-gray-50 dark:bg-gray-800 rounded-3xl px-5 py-3 mb-2">
								{(editedFiles ?? []).length > 0 && (
									<div className="flex items-center flex-wrap gap-2 -mx-2 mb-1">
										{editedFiles.map((file, fileIdx) => (
											<div key={fileIdx} className="relative group">
												{file.type === 'image' ? (
													<div className="relative flex items-center">
														<Image
															src={file.url}
															alt="input"
															imageClassName="size-14 rounded-xl object-cover"
														/>
														<button
															className="absolute -top-1 -right-1 bg-white text-black border border-white rounded-full"
															type="button"
															onClick={() => {
																const newFiles = [...editedFiles];
																newFiles.splice(fileIdx, 1);
																setEditedFiles(newFiles);
															}}
														>
															<svg className="size-4" viewBox="0 0 20 20" fill="currentColor">
																<path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
															</svg>
														</button>
													</div>
												) : (
													<div className="flex items-center gap-2 p-2 bg-gray-100 dark:bg-gray-700 rounded-lg">
														<span className="text-sm">{file.name || 'File'}</span>
													</div>
												)}
											</div>
										))}
									</div>
								)}

								<div className="max-h-96 overflow-auto">
									<textarea
										ref={textareaRef}
										className="bg-transparent outline-none w-full resize-none"
										value={editedContent}
										onChange={(e) => {
											setEditedContent(e.target.value);
											e.target.style.height = '';
											e.target.style.height = `${e.target.scrollHeight}px`;
										}}
										onKeyDown={(e) => {
											if (e.key === 'Escape') {
												cancelEdit();
											}
											if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
												handleEditConfirm();
											}
										}}
									/>
								</div>

								<div className="mt-2 mb-1 flex justify-between text-sm font-medium">
									<div>
										<button
											className="px-3.5 py-1.5 bg-gray-50 hover:bg-gray-100 dark:bg-gray-800 dark:hover:bg-gray-700 border border-gray-100 dark:border-gray-700 text-gray-700 dark:text-gray-200 transition rounded-3xl"
											onClick={() => handleEditConfirm(false)}
										>
											Save
										</button>
									</div>

									<div className="flex space-x-1.5">
										<button
											className="px-3.5 py-1.5 bg-white dark:bg-gray-900 hover:bg-gray-100 text-gray-800 dark:text-gray-100 transition rounded-3xl"
											onClick={cancelEdit}
										>
											Cancel
										</button>

										<button
											className="px-3.5 py-1.5 bg-gray-900 dark:bg-white hover:bg-gray-850 text-gray-100 dark:text-gray-800 transition rounded-3xl"
											onClick={() => handleEditConfirm(true)}
										>
											Send
										</button>
									</div>
								</div>
							</div>
						) : message.content !== '' ? (
							<div className="w-full">
								<div className={`flex ${chatBubble ? 'justify-end pb-1' : 'w-full'}`}>
									<div
										className={`rounded-3xl ${
											chatBubble
												? `max-w-[90%] px-4 py-1.5 bg-gray-50 dark:bg-gray-850 ${message.files ? 'rounded-tr-lg' : ''}`
												: 'w-full'
										}`}
									>
										{message.content && (
											<Markdown
												id={`${chatId}-${message.id}`}
												content={message.content}
												editCodeBlock={editCodeBlock}
												topPadding={topPadding}
											/>
										)}
									</div>
								</div>
							</div>
						) : null}

						{!edit && (
							<div
								className={`flex ${chatBubble ? 'justify-end' : ''} text-gray-600 dark:text-gray-500`}
							>
								{!chatBubble && siblings.length > 1 && (
									<div className="flex self-center" dir="ltr">
										<button
											className="self-center p-1 hover:bg-black/5 dark:hover:bg-white/5 dark:hover:text-white hover:text-black rounded-md transition"
											onClick={() => showPreviousMessage(message)}
										>
											<ChevronLeft className="size-3.5" strokeWidth={2.5} />
										</button>

										{messageIndexEdit ? (
											<div className="text-sm flex justify-center font-semibold self-center dark:text-gray-100 min-w-fit">
												<input
													type="number"
													value={siblingIndex + 1}
													min={1}
													max={siblings.length}
													className="bg-transparent font-semibold self-center dark:text-gray-100 min-w-fit outline-none w-8 text-center"
													onFocus={(e) => e.target.select()}
													onBlur={(e) => {
														gotoMessage(message, Number(e.target.value) - 1);
														setMessageIndexEdit(false);
													}}
													onKeyDown={(e) => {
														if (e.key === 'Enter') {
															gotoMessage(
																message,
																Number((e.target as HTMLInputElement).value) - 1
															);
															setMessageIndexEdit(false);
														}
													}}
												/>
												/{siblings.length}
											</div>
										) : (
											<div
												className="text-sm tracking-widest font-semibold self-center dark:text-gray-100 min-w-fit cursor-pointer"
												onDoubleClick={() => setMessageIndexEdit(true)}
											>
												{siblingIndex + 1}/{siblings.length}
											</div>
										)}

										<button
											className="self-center p-1 hover:bg-black/5 dark:hover:bg-white/5 dark:hover:text-white hover:text-black rounded-md transition"
											onClick={() => showNextMessage(message)}
										>
											<ChevronRight className="size-3.5" strokeWidth={2.5} />
										</button>
									</div>
								)}

								{!readOnly && (
									<Tooltip content="Edit" side="bottom">
										<button
											className={`${highContrastMode ? '' : 'invisible group-hover:visible'} p-1.5 hover:bg-black/5 dark:hover:bg-white/5 rounded-lg dark:hover:text-white hover:text-black transition`}
											onClick={handleEditMessage}
										>
											<Pencil className="size-4" strokeWidth={2.3} />
										</button>
									</Tooltip>
								)}

								{message.content && (
									<Tooltip content="Copy" side="bottom">
										<button
											className={`${highContrastMode ? '' : 'invisible group-hover:visible'} p-1.5 hover:bg-black/5 dark:hover:bg-white/5 rounded-lg dark:hover:text-white hover:text-black transition`}
											onClick={() => handleCopyToClipboard(message.content)}
										>
											<Copy className="size-4" strokeWidth={2.3} />
										</button>
									</Tooltip>
								)}

								{(currentUser?.role === 'admin' ||
									!!(currentUser?.permissions?.chat as Record<string, unknown>)?.delete_message) &&
									!readOnly &&
									(!isFirstMessage || siblings.length > 1) && (
										<Tooltip content="Delete" side="bottom">
											<button
												className={`${highContrastMode ? '' : 'invisible group-hover:visible'} p-1 rounded-sm dark:hover:text-white hover:text-black transition`}
												onClick={() => setShowDeleteConfirm(true)}
											>
												<Trash2 className="size-4" strokeWidth={2} />
											</button>
										</Tooltip>
									)}

								{chatBubble && siblings.length > 1 && (
									<div className="flex self-center" dir="ltr">
										<button
											className="self-center p-1 hover:bg-black/5 dark:hover:bg-white/5 dark:hover:text-white hover:text-black rounded-md transition"
											onClick={() => showPreviousMessage(message)}
										>
											<ChevronLeft className="size-3.5" strokeWidth={2.5} />
										</button>

										<div className="text-sm tracking-widest font-semibold self-center dark:text-gray-100 min-w-fit">
											{siblingIndex + 1}/{siblings.length}
										</div>

										<button
											className="self-center p-1 hover:bg-black/5 dark:hover:bg-white/5 dark:hover:text-white hover:text-black rounded-md transition"
											onClick={() => showNextMessage(message)}
										>
											<ChevronRight className="size-3.5" strokeWidth={2.5} />
										</button>
									</div>
								)}
							</div>
						)}
					</div>
				</div>
			</div>
		</>
	);
}

// src/lib/components/chat/Messages/UserMessage.svelte
<script lang="ts">
	import dayjs from 'dayjs';
	import { toast } from 'svelte-sonner';
	import { tick, onMount } from 'svelte';

	import { settings } from '$lib/stores';
	import { user as _user } from '$lib/stores';
	import { copyToClipboard as _copyToClipboard } from '$lib/utils';
	import { WEBUI_API_BASE_URL } from '$lib/constants';

	import Name from './Name.svelte';
	import ProfileImage from './ProfileImage.svelte';
	import Tooltip from '$lib/components/common/Tooltip.svelte';
	import FileItem from '$lib/components/common/FileItem.svelte';
	import Markdown from './Markdown.svelte';
	import Image from '$lib/components/common/Image.svelte';
	import DeleteConfirmDialog from '$lib/components/common/ConfirmDialog.svelte';

	import localizedFormat from 'dayjs/plugin/localizedFormat';
	dayjs.extend(localizedFormat);

	export let user;

	export let chatId;
	export let history;
	export let messageId;

	export let siblings;

	export let gotoMessage: Function;
	export let showPreviousMessage: Function;
	export let showNextMessage: Function;

	export let editMessage: Function;
	export let deleteMessage: Function;

	export let isFirstMessage: boolean;
	export let readOnly: boolean;
	export let editCodeBlock = true;
	export let topPadding = false;

	let showDeleteConfirm = false;

	let messageIndexEdit = false;

	let edit = false;
	let editedContent = '';
	let editedFiles = [];

	let messageEditTextAreaElement: HTMLTextAreaElement;

	let message = JSON.parse(JSON.stringify(history.messages[messageId]));
	$: if (history.messages) {
		if (JSON.stringify(message) !== JSON.stringify(history.messages[messageId])) {
			message = JSON.parse(JSON.stringify(history.messages[messageId]));
		}
	}

	const copyToClipboard = async (text) => {
		const res = await _copyToClipboard(text);
		if (res) {
			toast.success('Copying to clipboard was successful!');
		}
	};

	const editMessageHandler = async () => {
		edit = true;
		editedContent = message?.content ?? '';
		editedFiles = message.files;

		await tick();

		if (messageEditTextAreaElement) {
			messageEditTextAreaElement.style.height = '';
			messageEditTextAreaElement.style.height = `${messageEditTextAreaElement.scrollHeight}px`;

			messageEditTextAreaElement?.focus();
		}
	};

	const editMessageConfirmHandler = async (submit = true) => {
		if (!editedContent && (editedFiles ?? []).length === 0) {
			toast.error('Please enter a message or attach a file.');
			return;
		}

		editMessage(message.id, { content: editedContent, files: editedFiles }, submit);

		edit = false;
		editedContent = '';
		editedFiles = [];
	};

	const cancelEditMessage = () => {
		edit = false;
		editedContent = '';
		editedFiles = [];
	};

	const deleteMessageHandler = async () => {
		deleteMessage(message.id);
	};

	onMount(() => {
		// console.log('UserMessage mounted');
	});
</script>

<DeleteConfirmDialog
	bind:show={showDeleteConfirm}
	title={'Delete message?'}
	on:confirm={() => {
		deleteMessageHandler();
	}}
/>

<div
	class=" flex w-full user-message group"
	dir={$settings.chatDirection}
	id="message-{message.id}"
>
	{#if !($settings?.chatBubble ?? true)}
		<div class={`shrink-0 ltr:mr-3 rtl:ml-3 mt-1`}>
			<ProfileImage
				src={`${WEBUI_API_BASE_URL}/users/${user.id}/profile/image`}
				className={'size-8 user-message-profile-image'}
			/>
		</div>
	{/if}
	<div class="flex-auto w-0 max-w-full pl-1">
		{#if !($settings?.chatBubble ?? true)}
			<div>
				<Name>
					{#if message.user}
						{'You'}
						<span class=" text-gray-500 text-sm font-medium">{message?.user ?? ''}</span>
					{:else if $settings.showUsername || $_user.name !== user.name}
						{user.name}
					{:else}
						{'You'}
					{/if}

					{#if message.timestamp}
						<div
							class="self-center text-xs font-medium first-letter:capitalize ml-0.5 translate-y-[1px] {($settings?.highContrastMode ??
							false)
								? 'dark:text-gray-900 text-gray-100'
								: 'invisible group-hover:visible transition'}"
						>
							<Tooltip content={dayjs(message.timestamp * 1000).format('LLLL')}>
								<!-- 'Today at {{"LOCALIZED_TIME"}}') -->
								<!-- 'Yesterday at {{"LOCALIZED_TIME"}}' -->
								<!-- '{{"LOCALIZED_DATE"}} at {{"LOCALIZED_TIME"}}' -->

								<span class="line-clamp-1">{dayjs(message.timestamp * 1000).fromNow()}</span>
							</Tooltip>
						</div>
					{/if}
				</Name>
			</div>
		{:else if message.timestamp}
			<div class="flex justify-end pr-2 text-xs">
				<div
					class="text-[0.65rem] font-medium first-letter:capitalize mb-0.5 {($settings?.highContrastMode ??
					false)
						? 'dark:text-gray-100 text-gray-900'
						: 'invisible group-hover:visible transition text-gray-400'}"
				>
					<Tooltip content={dayjs(message.timestamp * 1000).format('LLLL')}>
						<span class="line-clamp-1">{dayjs(message.timestamp * 1000).fromNow()}</span>
					</Tooltip>
				</div>
			</div>
		{/if}

		<div class="chat-{message.role} w-full min-w-full markdown-prose">
			{#if edit !== true}
				{#if message.files}
					<div class="mb-1 w-full flex flex-col justify-end overflow-x-auto gap-1 flex-wrap">
						{#each message.files as file}
							<div class={($settings?.chatBubble ?? true) ? 'self-end' : ''}>
								{#if file.type === 'image'}
									<Image src={file.url} imageClassName=" max-h-96 rounded-lg" />
								{:else}
									<FileItem
										item={file}
										url={file.url}
										name={file.name}
										type={file.type}
										size={file?.size}
										small={true}
									/>
								{/if}
							</div>
						{/each}
					</div>
				{/if}
			{/if}

			{#if edit === true}
				<div class=" w-full bg-gray-50 dark:bg-gray-800 rounded-3xl px-5 py-3 mb-2">
					{#if (editedFiles ?? []).length > 0}
						<div class="flex items-center flex-wrap gap-2 -mx-2 mb-1">
							{#each editedFiles as file, fileIdx}
								{#if file.type === 'image'}
									<div class=" relative group">
										<div class="relative flex items-center">
											<Image
												src={file.url}
												alt="input"
												imageClassName=" size-14 rounded-xl object-cover"
											/>
										</div>
										<div class=" absolute -top-1 -right-1">
											<button
												class=" bg-white text-black border border-white rounded-full {($settings?.highContrastMode ??
												false)
													? ''
													: 'group-hover:visible invisible transition'}"
												type="button"
												on:click={() => {
													editedFiles.splice(fileIdx, 1);

													editedFiles = editedFiles;
												}}
											>
												<svg
													xmlns="http://www.w3.org/2000/svg"
													viewBox="0 0 20 20"
													fill="currentColor"
													class="size-4"
												>
													<path
														d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z"
													/>
												</svg>
											</button>
										</div>
									</div>
								{:else}
									<FileItem
										item={file}
										name={file.name}
										type={file.type}
										size={file?.size}
										loading={file.status === 'uploading'}
										dismissible={true}
										edit={true}
										on:dismiss={async () => {
											editedFiles.splice(fileIdx, 1);

											editedFiles = editedFiles;
										}}
										on:click={() => {
											console.log(file);
										}}
									/>
								{/if}
							{/each}
						</div>
					{/if}

					<div class="max-h-96 overflow-auto">
						<textarea
							id="message-edit-{message.id}"
							bind:this={messageEditTextAreaElement}
							class=" bg-transparent outline-hidden w-full resize-none"
							bind:value={editedContent}
							on:input={(e) => {
								e.target.style.height = '';
								e.target.style.height = `${e.target.scrollHeight}px`;
							}}
							on:keydown={(e) => {
								if (e.key === 'Escape') {
									document.getElementById('close-edit-message-button')?.click();
								}

								const isCmdOrCtrlPressed = e.metaKey || e.ctrlKey;
								const isEnterPressed = e.key === 'Enter';

								if (isCmdOrCtrlPressed && isEnterPressed) {
									document.getElementById('confirm-edit-message-button')?.click();
								}
							}}
						/>
					</div>

					<div class=" mt-2 mb-1 flex justify-between text-sm font-medium">
						<div>
							<button
								id="save-edit-message-button"
								class="px-3.5 py-1.5 bg-gray-50 hover:bg-gray-100 dark:bg-gray-800 dark:hover:bg-gray-700 border border-gray-100 dark:border-gray-700 text-gray-700 dark:text-gray-200 transition rounded-3xl"
								on:click={() => {
									editMessageConfirmHandler(false);
								}}
							>
								{'Save'}
							</button>
						</div>

						<div class="flex space-x-1.5">
							<button
								id="close-edit-message-button"
								class="px-3.5 py-1.5 bg-white dark:bg-gray-900 hover:bg-gray-100 text-gray-800 dark:text-gray-100 transition rounded-3xl"
								on:click={() => {
									cancelEditMessage();
								}}
							>
								{'Cancel'}
							</button>

							<button
								id="confirm-edit-message-button"
								class="px-3.5 py-1.5 bg-gray-900 dark:bg-white hover:bg-gray-850 text-gray-100 dark:text-gray-800 transition rounded-3xl"
								on:click={() => {
									editMessageConfirmHandler();
								}}
							>
								{'Send'}
							</button>
						</div>
					</div>
				</div>
			{:else if message.content !== ''}
				<div class="w-full">
					<div class="flex {($settings?.chatBubble ?? true) ? 'justify-end pb-1' : 'w-full'}">
						<div
							class="rounded-3xl {($settings?.chatBubble ?? true)
								? `max-w-[90%] px-4 py-1.5  bg-gray-50 dark:bg-gray-850 ${
										message.files ? 'rounded-tr-lg' : ''
									}`
								: ' w-full'}"
						>
							{#if message.content}
								<Markdown
									id={`${chatId}-${message.id}`}
									content={message.content}
									{editCodeBlock}
									{topPadding}
								/>
							{/if}
						</div>
					</div>
				</div>
			{/if}

			{#if edit !== true}
				<div
					class=" flex {($settings?.chatBubble ?? true)
						? 'justify-end'
						: ''}  text-gray-600 dark:text-gray-500"
				>
					{#if !($settings?.chatBubble ?? true)}
						{#if siblings.length > 1}
							<div class="flex self-center" dir="ltr">
								<button
									class="self-center p-1 hover:bg-black/5 dark:hover:bg-white/5 dark:hover:text-white hover:text-black rounded-md transition"
									on:click={() => {
										showPreviousMessage(message);
									}}
								>
									<svg
										xmlns="http://www.w3.org/2000/svg"
										fill="none"
										viewBox="0 0 24 24"
										stroke="currentColor"
										stroke-width="2.5"
										class="size-3.5"
									>
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											d="M15.75 19.5 8.25 12l7.5-7.5"
										/>
									</svg>
								</button>

								{#if messageIndexEdit}
									<div
										class="text-sm flex justify-center font-semibold self-center dark:text-gray-100 min-w-fit"
									>
										<input
											id="message-index-input-{message.id}"
											type="number"
											value={siblings.indexOf(message.id) + 1}
											min="1"
											max={siblings.length}
											on:focus={(e) => {
												e.target.select();
											}}
											on:blur={(e) => {
												gotoMessage(message, e.target.value - 1);
												messageIndexEdit = false;
											}}
											on:keydown={(e) => {
												if (e.key === 'Enter') {
													gotoMessage(message, e.target.value - 1);
													messageIndexEdit = false;
												}
											}}
											class="bg-transparent font-semibold self-center dark:text-gray-100 min-w-fit outline-hidden"
										/>/{siblings.length}
									</div>
								{:else}
									<!-- svelte-ignore a11y-no-static-element-interactions -->
									<div
										class="text-sm tracking-widest font-semibold self-center dark:text-gray-100 min-w-fit"
										on:dblclick={async () => {
											messageIndexEdit = true;

											await tick();
											const input = document.getElementById(`message-index-input-${message.id}`);
											if (input) {
												input.focus();
												input.select();
											}
										}}
									>
										{siblings.indexOf(message.id) + 1}/{siblings.length}
									</div>
								{/if}

								<button
									class="self-center p-1 hover:bg-black/5 dark:hover:bg-white/5 dark:hover:text-white hover:text-black rounded-md transition"
									on:click={() => {
										showNextMessage(message);
									}}
								>
									<svg
										xmlns="http://www.w3.org/2000/svg"
										fill="none"
										viewBox="0 0 24 24"
										stroke="currentColor"
										stroke-width="2.5"
										class="size-3.5"
									>
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											d="m8.25 4.5 7.5 7.5-7.5 7.5"
										/>
									</svg>
								</button>
							</div>
						{/if}
					{/if}
					{#if !readOnly}
						<Tooltip content={'Edit'} placement="bottom">
							<button
								class="{($settings?.highContrastMode ?? false)
									? ''
									: 'invisible group-hover:visible'} p-1.5 hover:bg-black/5 dark:hover:bg-white/5 rounded-lg dark:hover:text-white hover:text-black transition edit-user-message-button"
								on:click={() => {
									editMessageHandler();
								}}
							>
								<svg
									xmlns="http://www.w3.org/2000/svg"
									fill="none"
									viewBox="0 0 24 24"
									stroke-width="2.3"
									stroke="currentColor"
									class="w-4 h-4"
								>
									<path
										stroke-linecap="round"
										stroke-linejoin="round"
										d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125"
									/>
								</svg>
							</button>
						</Tooltip>
					{/if}

					{#if message?.content}
						<Tooltip content={'Copy'} placement="bottom">
							<button
								class="{($settings?.highContrastMode ?? false)
									? ''
									: 'invisible group-hover:visible'} p-1.5 hover:bg-black/5 dark:hover:bg-white/5 rounded-lg dark:hover:text-white hover:text-black transition"
								on:click={() => {
									copyToClipboard(message.content);
								}}
							>
								<svg
									xmlns="http://www.w3.org/2000/svg"
									fill="none"
									viewBox="0 0 24 24"
									stroke-width="2.3"
									stroke="currentColor"
									class="w-4 h-4"
								>
									<path
										stroke-linecap="round"
										stroke-linejoin="round"
										d="M15.666 3.888A2.25 2.25 0 0013.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 01-.75.75H9a.75.75 0 01-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 01-2.25 2.25H6.75A2.25 2.25 0 014.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 011.927-.184"
									/>
								</svg>
							</button>
						</Tooltip>
					{/if}

					{#if $_user?.role === 'admin' || ($_user?.permissions?.chat?.delete_message ?? false)}
						{#if !readOnly && (!isFirstMessage || siblings.length > 1)}
							<Tooltip content={'Delete'} placement="bottom">
								<button
									class="{($settings?.highContrastMode ?? false)
										? ''
										: 'invisible group-hover:visible'} p-1 rounded-sm dark:hover:text-white hover:text-black transition"
									on:click={() => {
										showDeleteConfirm = true;
									}}
								>
									<svg
										xmlns="http://www.w3.org/2000/svg"
										fill="none"
										viewBox="0 0 24 24"
										stroke-width="2"
										stroke="currentColor"
										class="w-4 h-4"
									>
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0"
										/>
									</svg>
								</button>
							</Tooltip>
						{/if}
					{/if}

					{#if $settings?.chatBubble ?? true}
						{#if siblings.length > 1}
							<div class="flex self-center" dir="ltr">
								<button
									class="self-center p-1 hover:bg-black/5 dark:hover:bg-white/5 dark:hover:text-white hover:text-black rounded-md transition"
									on:click={() => {
										showPreviousMessage(message);
									}}
								>
									<svg
										xmlns="http://www.w3.org/2000/svg"
										fill="none"
										viewBox="0 0 24 24"
										stroke="currentColor"
										stroke-width="2.5"
										class="size-3.5"
									>
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											d="M15.75 19.5 8.25 12l7.5-7.5"
										/>
									</svg>
								</button>

								{#if messageIndexEdit}
									<div
										class="text-sm flex justify-center font-semibold self-center dark:text-gray-100 min-w-fit"
									>
										<input
											id="message-index-input-{message.id}"
											type="number"
											value={siblings.indexOf(message.id) + 1}
											min="1"
											max={siblings.length}
											on:focus={(e) => {
												e.target.select();
											}}
											on:blur={(e) => {
												gotoMessage(message, e.target.value - 1);
												messageIndexEdit = false;
											}}
											on:keydown={(e) => {
												if (e.key === 'Enter') {
													gotoMessage(message, e.target.value - 1);
													messageIndexEdit = false;
												}
											}}
											class="bg-transparent font-semibold self-center dark:text-gray-100 min-w-fit outline-hidden"
										/>/{siblings.length}
									</div>
								{:else}
									<!-- svelte-ignore a11y-no-static-element-interactions -->
									<div
										class="text-sm tracking-widest font-semibold self-center dark:text-gray-100 min-w-fit"
										on:dblclick={async () => {
											messageIndexEdit = true;

											await tick();
											const input = document.getElementById(`message-index-input-${message.id}`);
											if (input) {
												input.focus();
												input.select();
											}
										}}
									>
										{siblings.indexOf(message.id) + 1}/{siblings.length}
									</div>
								{/if}

								<button
									class="self-center p-1 hover:bg-black/5 dark:hover:bg-white/5 dark:hover:text-white hover:text-black rounded-md transition"
									on:click={() => {
										showNextMessage(message);
									}}
								>
									<svg
										xmlns="http://www.w3.org/2000/svg"
										fill="none"
										viewBox="0 0 24 24"
										stroke="currentColor"
										stroke-width="2.5"
										class="size-3.5"
									>
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											d="m8.25 4.5 7.5 7.5-7.5 7.5"
										/>
									</svg>
								</button>
							</div>
						{/if}
					{/if}
				</div>
			{/if}
		</div>
	</div>
</div>
