// src/lib/components/chat/Messages/Message.svelte
<script lang="ts">
	import { createEventDispatcher } from 'svelte';
	const dispatch = createEventDispatcher();
	import { settings } from '$lib/stores';

	import MultiResponseMessages from './MultiResponseMessages.svelte';
	import ResponseMessage from './ResponseMessage.svelte';
	import UserMessage from './UserMessage.svelte';

	export let chatId;
	export let selectedModels = [];
	export let idx = 0;

	export let history;
	export let messageId;

	export let user;

	export let setInputText: Function = () => {};
	export let gotoMessage;
	export let showPreviousMessage;
	export let showNextMessage;
	export let updateChat;

	export let editMessage;
	export let saveMessage;
	export let deleteMessage;
	export let rateMessage;
	export let submitMessage;

	export let regenerateResponse;
	export let continueResponse;
	export let mergeResponses;

	export let addMessages;
	export let triggerScroll;
	export let readOnly = false;
	export let editCodeBlock = true;
	export let topPadding = false;
</script>

<div
	role="listitem"
	class="flex flex-col justify-between px-5 mb-3 w-full {($settings?.widescreenMode ?? null)
		? 'max-w-full'
		: 'max-w-5xl'} mx-auto rounded-lg group"
>
	{#if history.messages[messageId]}
		{#if history.messages[messageId].role === 'user'}
			<UserMessage
				{user}
				{chatId}
				{history}
				{messageId}
				isFirstMessage={idx === 0}
				siblings={history.messages[messageId].parentId !== null
					? (history.messages[history.messages[messageId].parentId]?.childrenIds ?? [])
					: (Object.values(history.messages)
							.filter((message) => message.parentId === null)
							.map((message) => message.id) ?? [])}
				{gotoMessage}
				{showPreviousMessage}
				{showNextMessage}
				{editMessage}
				{deleteMessage}
				{readOnly}
				{editCodeBlock}
				{topPadding}
			/>
		{:else if (history.messages[history.messages[messageId].parentId]?.models?.length ?? 1) === 1}
			<ResponseMessage
				{chatId}
				{history}
				{messageId}
				{selectedModels}
				isLastMessage={messageId === history.currentId}
				siblings={history.messages[history.messages[messageId].parentId]?.childrenIds ?? []}
				{setInputText}
				{gotoMessage}
				{showPreviousMessage}
				{showNextMessage}
				{updateChat}
				{editMessage}
				{saveMessage}
				{rateMessage}
				{submitMessage}
				{deleteMessage}
				{continueResponse}
				{regenerateResponse}
				{addMessages}
				{readOnly}
				{editCodeBlock}
				{topPadding}
			/>
		{:else}
			<MultiResponseMessages
				bind:history
				{chatId}
				{messageId}
				{selectedModels}
				isLastMessage={messageId === history?.currentId}
				{setInputText}
				{updateChat}
				{editMessage}
				{saveMessage}
				{rateMessage}
				{submitMessage}
				{deleteMessage}
				{continueResponse}
				{regenerateResponse}
				{mergeResponses}
				{triggerScroll}
				{addMessages}
				{readOnly}
				{editCodeBlock}
				{topPadding}
			/>
		{/if}
	{/if}
</div>

// next-app/src/components/chat/Messages/Message.tsx
'use client';

import { useAppStore } from '@/store';
import { UserMessage } from './UserMessage';
import { ResponseMessage } from './ResponseMessage';

interface HistoryMessage {
	id: string;
	role: string;
	content: string;
	model?: string;
	parentId: string | null;
	childrenIds: string[];
	models?: string[];
	files?: { type: string; url: string; name?: string }[];
	timestamp?: number;
	done?: boolean;
	error?: boolean | { content: string };
}

interface History {
	messages: Record<string, HistoryMessage>;
	currentId: string | null;
}

interface MessageProps {
	chatId: string;
	selectedModels: string[];
	idx: number;
	history: History;
	messageId: string;
	user: { id: string; name: string; role?: string };
	setInputText?: (text: string) => void;
	gotoMessage: (message: HistoryMessage, idx: number) => void;
	showPreviousMessage: (message: HistoryMessage) => void;
	showNextMessage: (message: HistoryMessage) => void;
	updateChat?: () => void;
	editMessage: (
		messageId: string,
		data: { content: string; files?: unknown[] },
		submit?: boolean
	) => void;
	saveMessage?: (messageId: string, message: HistoryMessage) => void;
	deleteMessage: (messageId: string) => void;
	rateMessage?: (messageId: string, rating: number) => void;
	submitMessage?: (prompt: string) => void;
	regenerateResponse?: (messageId?: string) => void;
	continueResponse?: () => void;
	mergeResponses?: () => void;
	addMessages?: (messages: unknown[]) => void;
	triggerScroll?: () => void;
	readOnly?: boolean;
	editCodeBlock?: boolean;
	topPadding?: boolean;
}

export function Message({
	chatId,
	selectedModels,
	idx,
	history,
	messageId,
	user,
	setInputText,
	gotoMessage,
	showPreviousMessage,
	showNextMessage,
	updateChat,
	editMessage,
	saveMessage,
	deleteMessage,
	rateMessage,
	submitMessage,
	regenerateResponse,
	continueResponse,
	mergeResponses,
	addMessages,
	triggerScroll,
	readOnly = false,
	editCodeBlock = true,
	topPadding = false
}: MessageProps) {
	const settings = useAppStore((s) => s.settings);

	const message = history.messages[messageId];

	if (!message) return null;

	const getSiblings = () => {
		if (message.parentId !== null) {
			return history.messages[message.parentId]?.childrenIds ?? [];
		}
		return (
			Object.values(history.messages)
				.filter((m) => m.parentId === null)
				.map((m) => m.id) ?? []
		);
	};

	const siblings = getSiblings();

	const parentModelsCount =
		message.parentId !== null ? (history.messages[message.parentId]?.models?.length ?? 1) : 1;

	const isUserMessage = message.role === 'user';
	const isMultiModel = parentModelsCount > 1;
	const isLastMessage = messageId === history.currentId;

	return (
		<div
			role="listitem"
			className={`flex flex-col justify-between px-5 mb-3 w-full ${
				settings?.widescreenMode ? 'max-w-full' : 'max-w-5xl'
			} mx-auto rounded-lg group`}
		>
			{isUserMessage ? (
				<UserMessage
					user={user}
					chatId={chatId}
					history={history}
					messageId={messageId}
					isFirstMessage={idx === 0}
					siblings={siblings}
					gotoMessage={gotoMessage}
					showPreviousMessage={showPreviousMessage}
					showNextMessage={showNextMessage}
					editMessage={editMessage}
					deleteMessage={deleteMessage}
					readOnly={readOnly}
					editCodeBlock={editCodeBlock}
					topPadding={topPadding}
				/>
			) : !isMultiModel ? (
				<ResponseMessage
					chatId={chatId}
					history={history}
					messageId={messageId}
					selectedModels={selectedModels}
					isLastMessage={isLastMessage}
					siblings={siblings}
					setInputText={setInputText}
					gotoMessage={gotoMessage}
					showPreviousMessage={showPreviousMessage}
					showNextMessage={showNextMessage}
					updateChat={updateChat}
					editMessage={editMessage}
					saveMessage={saveMessage}
					rateMessage={rateMessage}
					submitMessage={submitMessage}
					deleteMessage={deleteMessage}
					continueResponse={continueResponse}
					regenerateResponse={regenerateResponse}
					addMessages={addMessages}
					readOnly={readOnly}
					editCodeBlock={editCodeBlock}
					topPadding={topPadding}
				/>
			) : (
				<div className="text-sm text-gray-500">Multi-model responses not yet implemented</div>
			)}
		</div>
	);
}
