// next-app/src/components/chat/Messages/Markdown/MarkdownInlineTokens.tsx
'use client';

import DOMPurify from 'dompurify';
import type { Token } from 'marked';
import { WEBUI_BASE_URL } from '@/lib/constants';
import { unescapeHtml } from '@/lib/utils';
import { Image } from '@/components/common/Image';
import { KatexRenderer } from './KatexRenderer';

interface MarkdownInlineTokensProps {
  id: string;
  done?: boolean;
  tokens: Token[];
  sourceIds?: string[];
  onSourceClick?: (params: unknown) => void;
}

type TokenWithText = Token & {
  text?: string;
  href?: string;
  title?: string;
  tokens?: Token[];
  escapedText?: string;
  fileId?: string;
  raw?: string;
  ids?: number[];
  displayMode?: boolean;
};

export function MarkdownInlineTokens({
  id,
  done = true,
  tokens,
  sourceIds = [],
  onSourceClick,
}: MarkdownInlineTokensProps) {
  const renderToken = (token: TokenWithText, tokenIdx: number) => {
    const key = `${id}-${tokenIdx}`;

    switch (token.type) {
      case 'escape':
        return <span key={key}>{unescapeHtml(token.text || '')}</span>;

      case 'html':
        if (typeof window === 'undefined') return null;
        return (
          <span
            key={key}
            dangerouslySetInnerHTML={{
              __html: DOMPurify.sanitize(token.raw || token.text || ''),
            }}
          />
        );

      case 'link':
        return (
          <a
            key={key}
            href={token.href}
            target="_blank"
            rel="nofollow noopener noreferrer"
            title={token.title}
          >
            {token.tokens ? (
              <MarkdownInlineTokens
                id={`${id}-a`}
                tokens={token.tokens}
                onSourceClick={onSourceClick}
                done={done}
              />
            ) : (
              token.text
            )}
          </a>
        );

      case 'image':
        return <Image key={key} src={token.href || ''} alt={token.text || ''} />;

      case 'strong':
        return (
          <strong key={key}>
            <MarkdownInlineTokens
              id={`${id}-strong`}
              tokens={token.tokens || []}
              onSourceClick={onSourceClick}
            />
          </strong>
        );

      case 'em':
        return (
          <em key={key}>
            <MarkdownInlineTokens
              id={`${id}-em`}
              tokens={token.tokens || []}
              onSourceClick={onSourceClick}
            />
          </em>
        );

      case 'codespan':
        return (
          <code
            key={key}
            className="codespan px-1.5 py-0.5 text-sm rounded-md bg-gray-100 dark:bg-gray-800"
          >
            {token.text}
          </code>
        );

      case 'br':
        return <br key={key} />;

      case 'del':
        return (
          <del key={key}>
            <MarkdownInlineTokens
              id={`${id}-del`}
              tokens={token.tokens || []}
              onSourceClick={onSourceClick}
            />
          </del>
        );

      case 'inlineKatex':
        return token.text ? (
          <KatexRenderer key={key} content={token.text} displayMode={false} />
        ) : null;

      case 'iframe':
        return (
          <iframe
            key={key}
            src={`${WEBUI_BASE_URL}/api/v1/files/${token.fileId}/content`}
            title={token.fileId}
            width="100%"
            frameBorder="0"
            onLoad={(e) => {
              try {
                const iframe = e.currentTarget;
                if (iframe.contentWindow) {
                  iframe.style.height =
                    iframe.contentWindow.document.body.scrollHeight + 20 + 'px';
                }
              } catch {
                // Ignore cross-origin errors
              }
            }}
          />
        );

      case 'footnote':
        if (typeof window === 'undefined') return null;
        return (
          <span
            key={key}
            dangerouslySetInnerHTML={{
              __html: DOMPurify.sanitize(
                `<sup class="footnote-ref footnote-ref-text">${token.escapedText || ''}</sup>`
              ),
            }}
          />
        );

      case 'citation':
        if (token.ids && token.ids.length > 0) {
          return (
            <span key={key} className="citation-ref">
              {token.ids.map((sourceId: number) => (
                <button
                  key={sourceId}
                  className="citation-button text-xs text-blue-500 hover:underline mx-0.5"
                  onClick={() => onSourceClick?.({ sourceId: sourceId - 1, sourceIds })}
                >
                  [{sourceId}]
                </button>
              ))}
            </span>
          );
        }
        return null;

      case 'text':
        if (token.tokens) {
          return (
            <span key={key}>
              <MarkdownInlineTokens
                id={`${id}-text`}
                tokens={token.tokens}
                onSourceClick={onSourceClick}
                done={done}
              />
            </span>
          );
        }
        return <span key={key}>{token.text}</span>;

      default:
        return token.text ? <span key={key}>{token.text}</span> : null;
    }
  };

  return <>{tokens.map((token, idx) => renderToken(token as TokenWithText, idx))}</>;
}

// src/lib/components/chat/Messages/Markdown/MarkdownInlineTokens.svelte
<script lang="ts">
	import DOMPurify from 'dompurify';
	import type { Token } from 'marked';
	import { WEBUI_BASE_URL } from '$lib/constants';
	import { unescapeHtml } from '$lib/utils';

	import Image from '$lib/components/common/Image.svelte';
	import KatexRenderer from './KatexRenderer.svelte';
	import HtmlToken from './HTMLToken.svelte';
	import TextToken from './MarkdownInlineTokens/TextToken.svelte';
	import CodespanToken from './MarkdownInlineTokens/CodespanToken.svelte';
	import MentionToken from './MarkdownInlineTokens/MentionToken.svelte';
	import SourceToken from './SourceToken.svelte';

	export let id: string;
	export let done = true;
	export let tokens: Token[];
	export let sourceIds = [];
	export let onSourceClick: Function = () => {};
</script>

{#each tokens as token, tokenIdx (tokenIdx)}
	{#if token.type === 'escape'}
		{unescapeHtml(token.text)}
	{:else if token.type === 'html'}
		<HtmlToken {id} {token} {onSourceClick} />
	{:else if token.type === 'link'}
		{#if token.tokens}
			<a href={token.href} target="_blank" rel="nofollow" title={token.title}>
				<svelte:self id={`${id}-a`} tokens={token.tokens} {onSourceClick} {done} />
			</a>
		{:else}
			<a href={token.href} target="_blank" rel="nofollow" title={token.title}>{token.text}</a>
		{/if}
	{:else if token.type === 'image'}
		<Image src={token.href} alt={token.text} />
	{:else if token.type === 'strong'}
		<strong><svelte:self id={`${id}-strong`} tokens={token.tokens} {onSourceClick} /></strong>
	{:else if token.type === 'em'}
		<em><svelte:self id={`${id}-em`} tokens={token.tokens} {onSourceClick} /></em>
	{:else if token.type === 'codespan'}
		<CodespanToken {token} {done} />
	{:else if token.type === 'br'}
		<br />
	{:else if token.type === 'del'}
		<del><svelte:self id={`${id}-del`} tokens={token.tokens} {onSourceClick} /></del>
	{:else if token.type === 'inlineKatex'}
		{#if token.text}
			<KatexRenderer content={token.text} displayMode={false} />
		{/if}
	{:else if token.type === 'iframe'}
		<iframe
			src="{WEBUI_BASE_URL}/api/v1/files/{token.fileId}/content"
			title={token.fileId}
			width="100%"
			frameborder="0"
			on:load={(e) => {
				try {
					e.currentTarget.style.height =
						e.currentTarget.contentWindow.document.body.scrollHeight + 20 + 'px';
				} catch {}
			}}
		></iframe>
	{:else if token.type === 'mention'}
		<MentionToken {token} />
	{:else if token.type === 'footnote'}
		{@html DOMPurify.sanitize(
			`<sup class="footnote-ref footnote-ref-text">${token.escapedText}</sup>`
		) || ''}
	{:else if token.type === 'citation'}
		<SourceToken {id} {token} {sourceIds} onClick={onSourceClick} />
		<!-- {#if token.ids && token.ids.length > 0}
			{#each token.ids as sourceId}
				<Source id={sourceId - 1} title={sourceIds[sourceId - 1]} onClick={onSourceClick} />
			{/each}
		{/if} -->
	{:else if token.type === 'text'}
		<TextToken {token} {done} />
	{/if}
{/each}
